### ISSUE TITLE
Question about reproduce SmoothDARTS on PTB

### ISSUE THREAD

**Issue by fortunechen** [xiangning-chen/SmoothDARTS#6]
Hi, xiangning.

Thanks for your great work and opensoure code.  

I evaluate(training for 300 epoches) the initial architecture and the architectures after searching for 50 epoch by `random` and `pgd` repectively.  The results are weird as below. 

![image](https://user-images.githubusercontent.com/26025440/109378283-45a5e300-790c-11eb-9bcb-85355ba64a6e.png)

> 1. The architecture does not improve after searching in 4 runs

> 2.  The random architecture seems better than your searched result.
And I evaluate your results in the last line. Every initial architecture is better than your `random` architecture and one of initial architecture is better than your `pgd` architecture.

> 3. I evaluate architecture after training 50 epochs, did you use early stopping ?

Could you please help me figure it out? Thx!

BR

**Comment by xiangning-chen** [comment]
Hi,

Thanks for your attention. The RNN cell retraining requires many epochs, we simply follow the DARTS settings here (https://github.com/quark0/darts/blob/master/rnn/train.py#L34).
Also, the current differentiable NAS methods indeed perform not good on RNN space from my experience (maybe worse than random).
Probably because that its space only contains parameter-free operations like sigmoid, relu, etc.

**Comment by fortunechen** [comment]
Thx for your answer.
